version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-notes
    restart: always
    ports:
      - '5442:5432'
    volumes:
      - /root/database/psql/psql-notes:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=notes
    networks:
      - anhdev
  redis:
    image: redis:latest
    container_name: redis-notes
    restart: always
    ports:
      - '6389:6379'
    volumes:
      - /root/database/redis/redis-notes/data:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - anhdev
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $$REDIS_PASSWORD'

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbit-notes'
    ports:
      - 5682:5672
      - 15682:15672
    volumes:
      - /root/database/rabbit/rabbit-notes/data/:/var/lib/rabbit-notes/
      - /root/database/rabbit/rabbit-notes/log/:/var/log/rabbit-notes/
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    networks:
      - anhdev

networks:
  anhdev:
    name: anhdev
    external: true

volumes:
  psql-notes:
  redis-notes:
  rabbit-notes:
